version: '3.8'

services:
  postgres:
    image: postgres:17.5
    container_name: vpp-postgres
    environment:
      POSTGRES_DB: vpp
      POSTGRES_USER: vpp_user
      POSTGRES_PASSWORD: vpp_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U vpp_user -d vpp"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    name: vpp-postgres-data