name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Set up Docker for TestContainers
      uses: docker/setup-buildx-action@v2

    - name: Build and Test
      run: mvn -B clean verify
      env:
        TESTCONTAINERS_DOCKER_SOCKET_OVERRIDE: /var/run/docker.sock
        DOCKER_HOST: unix:///var/run/docker.sock

    - name: Generate Coverage Report
      run: mvn jacoco:report

    - name: Upload Coverage Report
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: target/site/jacoco/
